[fix] CICD

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -32,28 +32,33 @@ jobs:
             UserKnownHostsFile /dev/null
             LogLevel ERROR
           EOF
+
       - name: Test SSH Connection
         run: |
           ssh -vvv playground-umc-7th "echo '✅ SSH Connection Successful'"
+
       - name: Ensure EBS is Mounted and Fix Permissions
         run: |
           ssh playground-umc-7th '
             if ! mountpoint -q /mnt/ebs; then
-              echo "❌ EBS is not mounted!"
-              exit 1
+              echo "⚠️ EBS is not mounted. Mounting now..."
+              sudo mount /dev/xvdbf /mnt/ebs || { echo "❌ Failed to mount EBS"; exit 1; }
             fi
             sudo chown -R ubuntu:ubuntu /mnt/ebs
             sudo chmod -R 775 /mnt/ebs
           '
+
       - name: Copy Workspace to EBS
         run: |
           rsync -avz --exclude={'.git','dist','/.env','node_modules','*.log'} ./ playground-umc-7th:/mnt/ebs/travel_box_backend/
+
       - name: Install Dependencies
         run: |
           ssh playground-umc-7th '
             cd /mnt/ebs/travel_box_backend
             npm install
           '
+
       - name: Create .env file
         run: |
           ssh playground-umc-7th 'cat > /mnt/ebs/travel_box_backend/.env << EOF
@@ -72,24 +77,27 @@ jobs:
           ELASTIC_SEARCH=${{ secrets.ELASTIC_SEARCH }}
           ELASTIC_SEARCH_API=${{ secrets.ELASTIC_SEARCH_API }}
           EOF'
+
       - name: Kill Existing Node Processes
         run: |
           ssh playground-umc-7th 'pkill node || true'
+
       - name: Start Application in Background
         run: |
           ssh playground-umc-7th '
             cd /mnt/ebs/travel_box_backend
             nohup npm run dev > app.log 2> app.error.log &
           '
+
       - name: Check if Application is Running
         run: |
           ssh playground-umc-7th '
             sleep 10  # Give some time for the application to start
             if pgrep -x "node" > /dev/null
             then
-              echo "Application is running."
+              echo "✅ Application is running."
             else
-              echo "Application failed to start."
+              echo "❌ Application failed to start."
               exit 1
             fi
           '
